service: notes-app

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

plugins:
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get

custom:
  dotenv:
    include:
      - LOG_LEVEL # workaround for absence of exclude